CC = gcc
CFLAGS  = -g -Wall
TARGET=wordsearch
TARGET1=Array2D
TARGET2=MatrixMult
TARGET3=cyclic_ll

all:	
	$(CC) wordsearch.c -o $(TARGET) 
	# $(CC) Array2D.c -o $(TARGET1)
	# $(CC) MatrixMult.c -o $(TARGET2)

clean: 
	rm -f $(TARGET)
	# rm *.o $(TARGET)
run:
	./wordsearch puzzle1.txt

run1:
	./wordsearch test.txt


